add_webpack:
	wasm-pack build --target web

Bundle:
	rollup ./main.js --format iife --file ./pkg/bundle.js


webpack:
	python -m http.server 8080

trunk:
	trunk serve


kill:
	kill -INT $(lsof -t -i :8080)

run:
	cargo run

update:
	cargo update